@localhost = https://localhost:5154

### start random forecasts
POST {{localhost}}/forecast/random

### start 5 random forecasts
POST {{localhost}}/forecast/random?numberOfForecasts=5

### start the same forecasts
POST {{localhost}}/forecast/deterministic

### start the same 5 forecasts
POST {{localhost}}/forecast/deterministic?numberOfForecasts=5

###